stages:
  - docker build
  - docker test

variables:
  CONTAINER_TEST_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

docker-build:
  image: docker:stable
  stage: docker build
  services:
    - docker:dind
  environment:
    name: production
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - schedules

docker-run-test:
  image: docker:stable
  stage: docker test
  services:
    - docker:dind
  environment:
    name: production
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run -d -p 5022:5001 --name dm $CONTAINER_TEST_IMAGE
    - docker ps -a
    - docker stop dm
    - docker rm dm
  only:
    - schedules
